# Generated by Django 3.0 on 2021-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_name', models.CharField(max_length=100)),
                ('num_magnitude', models.DecimalField(decimal_places=2, max_digits=3)),
                ('des_place', models.CharField(max_length=200)),
                ('flag_alarm', models.BooleanField()),
                ('des_country', models.CharField(blank=True, max_length=50, null=True)),
                ('time_detected', models.DateTimeField()),
                ('time_created_db', models.DateTimeField(auto_now_add=True)),
                ('time_updated_db', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
